version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /opt/homeassistant:/config
    environment:
      TZ: "${TZ}"
    restart: unless-stopped
    privileged: true
    network_mode: host
    depends_on:
      - mosquitto

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    network_mode: host
    volumes:
      - /opt/mosquitto/config:/mosquitto/config
      - /opt/mosquitto/data:/mosquitto/data
      - /opt/mosquitto/log:/mosquitto/log
    environment:
      TZ: "${TZ}"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: "koenkk/zigbee2mqtt:latest"
    restart: unless-stopped
    network_mode: host
    volumes:
      - /opt/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2419875-if00:/dev/ttyACM0
    environment:
      TZ: "${TZ}"
    depends_on:
      - mosquitto
  
  scrypted:
    image: koush/scrypted
    container_name: scrypted
    environment:
      - SCRYPTED_WEBHOOK_UPDATE_AUTHORIZATION=Bearer PKf2aBmbt95jP2jYL6lgNeBr0h
      - SCRYPTED_WEBHOOK_UPDATE=http://localhost:10444/v1/update
    restart: unless-stopped
    network_mode: host
    volumes:
      - /opt/scrypted:/server/volume
      - /media/usb-storage/nvr:/media/external
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    labels:
      - "com.centurylinklabs.watchtower.scope=scrypted"

  watchtower:
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=PKf2aBmbt95jP2jYL6lgNeBr0h
      - WATCHTOWER_HTTP_API_UPDATE=true
      - WATCHTOWER_SCOPE=scrypted
      - WATCHTOWER_HTTP_API_PERIODIC_POLLS=true
    image: containrrr/watchtower
    container_name: scrypted-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "com.centurylinklabs.watchtower.scope=scrypted"
    ports:
      - 10444:8080
    command: --interval 604800 --cleanup
